[package]
name = "day20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utility = { path = "../utility" }
itertools = "0.10.5"
regex = "1"
lazy_static = "1.4.0"
memoize = "0.3.3"
